general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follows_focus: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: false

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # Whether to center new floating windows.
  center_new_floating_windows: true

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "false"

gaps:
  # Gap between adjacent windows.
  inner_gap: "4px"

  # Gap between windows and the screen edge.
  outer_gap: "4px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#6f00ff"

  inactive:
    enabled: false
    color: "#ba0048"

bar:
  height: "30px"
  position: "bottom"
  opacity: 0.75
  background: "#20242cc4"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "16px"
  padding: "4px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  component_separator:
    label: "  "
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
    - type: "music"
      label_not_playing: ""
      label_paused: "{song_title} - {artist_name}"
      label_playing: "{song_title} - {artist_name} ▶"
      max_title_length: 20
      max_artist_length: 20
    - type: "volume"
      label_low: "🔈{volume_level}%"
      label_medium: "🔉{volume_level}%"
      label_high: "🔊{volume_level}%"
      label_mute: "🔇{volume_level}%"
  components_center:
    # - type: "window title"
    - type: "clock"
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: "hh:mm tt  ddd MMM d"
    - type: "weather"
      latitude: 40.635750
      longitude: 22.946709
      label: "{temperature_celsius}°C"
      label_sun: "☀️ {temperature_celsius}°C"
      label_moon: "🌙 {temperature_celsius}°C"
      label_cloud_moon: "🌙☁️ {temperature_celsius}°C"
      label_cloud_sun: "⛅ {temperature_celsius}°C"
      label_cloud_moon_rain: "🌙🌧️ {temperature_celsius}°C"
      label_cloud_sun_rain: "🌦️ {temperature_celsius}°C"
      label_cloud_rain: "🌧️ {temperature_celsius}°C"
      label_snow_flake: "❄️ {temperature_celsius}°C"
      label_thunderstorm: "⚡ {temperature_celsius}°C"
      label_cloud: "☁️ {temperature_celsius}°C"
  components_right:
    - type: "cpu"
      label: "CPU {percent_usage}%"
      refresh_interval_ms: 1000
    - type: "gpu"
      label: "GPU {percent_usage}%"
      refresh_interval_ms: 1000
    - type: "system tray"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#ffffff33"
      margin: "0 4px"
      padding: "0 8px"
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
  - name: "0"

window_rules:
  # ignore
   
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"

  # Do not manage picture-in-picture windows for browsers. Note that the default is for
  # English; change `match_title` to the window's title if you use another language.
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

  - command: "ignore"
    match_title: "Volume Mixer.*"

  - command: "ignore"
    match_process_name: "7zG"

  - command: "ignore"
    match_process_name: "mpv"

  # floating

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # - command: "set floating"
    # match_process_name: "explorer"

  - command: "set floating"
    match_process_name: "godot"

  - command: "set floating"
    match_process_name: "Everything"

  - command: "set floating"
    match_process_name: "MailClient"

  - command: "set floating"
    match_process_name: "qbittorrent"

  - command: "set floating"
    match_process_name: "vlc"

  - command: "set floating"
    match_process_name: "parsecd"

  - command: "set floating"
    match_process_name: "7zFM"

  - command: "set floating"
    match_title: "Calculator"

  - command: "set floating"
    match_process_name: "studio64"

  # resize

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders -1px -8px -8px -8px"
    match_process_name: "steamwebhelper"

  - command: "resize borders -1px -8px -8px -8px"
    match_process_name: "EpicGamesLauncher"

  # workspace 1

  - command: "move to workspace 1"
    match_title: "General"

  - command: "move to workspace 1"
    match_title: "Watch"

  - command: "move left"
    match_title: "General"

  - command: "move right"
    match_title: "Watch"

  # workspace 2

  - command: "move to workspace 2"
    match_title: "Learn"

  - command: "move right"
    match_title: "Learn"

  # workspace 5

  - command: "move to workspace 5"
    match_title: "Customize"

  # workspace 6

  # - command: "move to workspace 6"
    # match_process_name: "WindowsTerminal"

  # workspace 8

  - command: "move to workspace 8"
    match_process_name: "steamwebhelper"

  - command: "move to workspace 8"
    match_process_name: "Battle.net"

  - command: "move to workspace 8"
    match_process_name: "EpicGamesLauncher"

  - command: "move to workspace 8"
    match_process_name: "GalaxyClient"

  - command: "move to workspace 8"
    match_process_name: "Playnite.DesktopApp"

  - command: "move to workspace 8"
    match_title: "Games"

  - command: "move to workspace 8"
    match_process_name: "Balatro"

  - command: "move left"
    match_process_name: "steamwebhelper"

  - command: "move left"
    match_process_name: "Battle.net"

  - command: "move left"
    match_process_name: "EpicGamesLauncher"

  - command: "move left"
    match_process_name: "GalaxyClient"

  - command: "move left"
    match_process_name: "Playnite.DesktopApp"

  - command: "move right"
    match_title: "Games"

  # workspace 9

  - command: "move to workspace 9"
    match_process_name: "Spotify"

  - command: "move to workspace 9"
    match_title: "Music"

  - command: "move left"
    match_process_name: "Spotify"

  - command: "move right"
    match_title: "Music"

  # workspace 0

  - command: "move to workspace 0"
    match_process_name: "Discord"

  - command: "move to workspace 0"
    match_process_name: "Telegram"

  - command: "move left"
    match_process_name: "Discord"

  - command: "move right"
    match_process_name: "Telegram"

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H"]
      - command: "resize width +2%"
        bindings: ["L"]
      - command: "resize height +2%"
        bindings: ["K"]
      - command: "resize height -2%"
        bindings: ["J"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+H"]
  - command: "focus right"
    bindings: ["Alt+L"]
  - command: "focus up"
    bindings: ["Alt+K"]
  - command: "focus down"
    bindings: ["Alt+J"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+H"]
  - command: "move right"
    bindings: ["Alt+Shift+L"]
  - command: "move up"
    bindings: ["Alt+Shift+K"]
  - command: "move down"
    bindings: ["Alt+Shift+J"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  # - command: "binding mode resize"
    # binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "Alt+Space"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window.
  - command: "close"
    binding: "Alt+Shift+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec wt"
    binding: "Alt+N"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"
  - command: "focus workspace 0"
    binding: "Alt+0"

  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "Alt+A"
  - command: "move workspace right"
    binding: "Alt+F"
  - command: "move workspace up"
    binding: "Alt+D"
  - command: "move workspace down"
    binding: "Alt+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]
  - commands: ["move to workspace 0", "focus workspace 0"]
    bindings: ["Alt+Shift+0"]
